#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/Endocrinologia/D13/Virtual/18-03-2022/ 
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/Genecologia/D9/Virtual/15-03-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/Endocrinologia/D10/Virtual/22-03-2022/ 
bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/Genecologia/D9/Virtual/29-03-2022
bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/Genecologia/D9/Virtual/15-03-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/Genecologia/D14/Virtual/25-02-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/MedGeral/D4/Virtual/17-03-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/MedGeral/D4/Presential/15-03-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/MedGeral/D16/Presential/11-03-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/MedGeral/D5/Presential/17-03-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/MedGeral/D5/Virtual/10-03-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/MedGeral/D5/Virtual/03-03-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/MedGeral/D7/Virtual/04-03-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/MedGeral/D7/Virtual/18-03-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/MedGeral/D16/Presential/18-03-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/MedGeral/D16/Presential/11-03-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/MedGeral/D4/Virtual/24-02-2022
bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/Endocrinologia/D3/Presential/24-03-2022
bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/Endocrinologia/D3/Presential/28-03-2022
bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/Endocrinologia/D10/Presential/25-03-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/Genecologia/D14/Virtual/18-03-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/Neurologia/D11/Virtual/11-03-2022
bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/Neurologia/D8/Virtual/30-03-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/Neurologia/D8/Presential/23-02-2022

