#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/Endocrinologia/D15/Virtual/05-04-2022 
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/Genecologia/D9/Virtual/15-03-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/Endocrinologia/D10/Virtual/05-04-2022 
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/Endocrinologia/D10/Virtual/25-03-2022 
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/Genecologia/D6/Presential/06-04-2022
bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/Genecologia/D9/Presential/14-04-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/Genecologia/D14/Presential/12-04-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/Genecologia/D14/Virtual/08-04-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/Genecologia/D14/Virtual/01-04-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/MedGeral/D4/Virtual/02-04-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/MedGeral/D4/Virtual/07-04-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/MedGeral/D4/Virtual/24-03-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/MedGeral/D4/Virtual/26-03-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/MedGeral/D4/Virtual/31-03-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/MedGeral/D16/Virtual/22-03-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/MedGeral/D16/Virtual/29-03-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/MedGeral/D16/Virtual/07-04-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/MedGeral/D16/Virtual/15-03-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/MedGeral/D16/Virtual/23-03-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/MedGeral/D5/Virtual/03-03-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/MedGeral/D7/Virtual/07-04-2022

#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/MedGeral/D16/Presential/11-03-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/MedGeral/D4/Virtual/24-02-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/Endocrinologia/D3/Presential/24-03-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/Endocrinologia/D3/Presential/28-03-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/Endocrinologia/D10/Presential/25-03-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/Genecologia/D14/Presential/08-04-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/Neurologia/D11/Virtual/11-03-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/Neurologia/D8/Virtual/06-04-2022
#bash landmarking_script.sh -d /media/vislab/My_Passport/Tese/videos/Neurologia/D8/Presential/23-02-2022

